runtime: python27
api_version: 1
threadsafe: true

libraries:

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.py
- url: /.*
  script: project.html
# [END handlers]